# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='shelves',
        ),
        migrations.AddField(
            model_name='goodssku',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='商品分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='is_on_sale',
            field=models.BooleanField(choices=[(False, '下架'), (True, '上架')], default=False, verbose_name='是否上架'),
        ),
    ]
