# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190125_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityZoneGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('Create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='商品SKU')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='activityzone',
            old_name='shelves',
            new_name='is_on_sale',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unitname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='activityzonegoods',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ActivityZone', verbose_name='活动专区'),
        ),
    ]
