# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, '手机号至少11位')], verbose_name='用户名,使用手机号'),
        ),
    ]
