# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190120_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterModelTable(
            name='users',
            table='sp_user',
        ),
    ]
