# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190120_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='phone',
        ),
    ]
