# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190121_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='username',
        ),
    ]
